const BRAND_MAP = {
  'VIPS': '빕스',
  'STARBUCKS': '스타벅스',
  'MCDONALD': '맥도날드',
  'KFC': '케이에프씨',
  'CU': '씨유',
  'YES24': '예스이십사',
  'BURGER KING': '버거킹',
  'BURGERKING': '버거킹',
  'SUBWAY': '써브웨이',
  'SHAKE SHACK': '쉐이크쑑',
  'FIVE GUYS': '파이브가이즈',
  'PIZZA HUT': '피자헛',
  'DOMINO': '도미노',
  'PAPA JOHN': '파파존스',
  'OUTBACK': '아웃백',
  'DUNKIN': '던킨',
  'SMOOTHIE KING': '스무디킹',
  'BLUE BOTTLE': '블루보틀',
  '7-ELEVEN': '세븐일레븐',
  '7ELEVEN': '세븐일레븐',
  'MINISTOP': '미니스톱',
  'E-MART': '이마트',
  'HOMEPLUS': '홈플러스',
  'COSTCO': '코스트코',
  'TRADERS': '트레이더스',
  'DAISO': '다이소',
  'IKEA': '이케아',
  'COUPANG': '쿠팡',
  'AUCTION': '옥션',
  'AMAZON': '아마존',
  'ALIEXPRESS': '알리익스프레스',
  'TEMU': '테무',
  'SHEIN': '쉬인',
  'UNIQLO': '유니클로',
  'ZARA': '자라',
  '8SECONDS': '에잇세컨즈',
  'NIKE': '나이키',
  'ADIDAS': '아디다스',
  'NEW BALANCE': '뉴발란스',
  'THE NORTH FACE': '노스페이스',
  'POLO': '폴로',
  'MUSINSA': '무신사',
  'UBER': '우버',
  'NETFLIX': '넷플릭스',
  'SPOTIFY': '스포티파이',
  'STEAM': '스팀',
  'PLAYSTATION': '플레이스테이션',
  'UDEMY': '유데미',
  'COURSERA': '코세라'
};

const CARD_TO_BANK_MAP = {
  'KB국민카드': '국민은행',
  '국민카드': '국민은행',
  'KB국민체크카드': '국민은행',
  '국민체크카드': '국민은행',
  '신한카드': '신한은행',
  '신한체크카드': '신한은행',
  '하나카드': '하나은행',
  '하나체크카드': '하나은행',
  '우리카드': '우리은행',
  '우리체크카드': '우리은행',
  'NH농협카드': '농협은행',
  '농협카드': '농협은행',
  'NH농협체크카드': '농협은행',
  '농협체크카드': '농협은행',
  '토스': '토스뱅크',
  '토스카드': '토스뱅크',
  '토스체크카드': '토스뱅크',
  '카카오': '카카오뱅크',
  '카카오카드': '카카오뱅크',
  '카카오체크카드': '카카오뱅크',
  '케이뱅크카드': '케이뱅크',
  'BC카드': '계좌이체',
  'BC체크카드': '계좌이체',
  '삼성카드': '계좌이체',
  '삼성체크카드': '계좌이체',
  '현대카드': '계좌이체',
  '현대체크카드': '계좌이체',
  '롯데카드': '계좌이체',
  '롯데체크카드': '계좌이체'
};

const BANK_HINTS = {
  '국민': '국민은행',
  'KB국민': '국민은행',
  '신한': '신한은행',
  '우리': '우리은행',
  '하나': '하나은행',
  '농협': '농협은행',
  'NH': '농협은행',
  '기업': '기업은행',
  'IBK': '기업은행',
  '우체국': '우체국',
  '새마을': '새마을금고',
  '신협': '신협',
  '수협': '수협은행',
  '대구': '대구은행',
  '부산': '부산은행',
  '광주': '광주은행',
  '전북': '전북은행',
  '경남': '경남은행',
  '제주': '제주은행',
  '카카오': '카카오뱅크',
  '토스': '토스뱅크',
  '케이': '케이뱅크',
  'K뱅크': '케이뱅크'
};

let franchisePresets = [];
try {
  franchisePresets = require('../franchise_presets').FRANCHISE_PRESETS || [];
} catch (e) {
  console.warn('[Parser] Failed to load franchise presets:', e.message);
}

module.exports = {
  BRAND_MAP,
  CARD_TO_BANK_MAP,
  BANK_HINTS,
  franchisePresets
};
